# Generated by Django 4.1.2 on 2022-11-03 21:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "generated_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="post", name="body",),
        migrations.AddField(
            model_name="post", name="answers", field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="event_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.DeleteModel(name="Image",),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="post.category",
            ),
        ),
    ]
