# Generated by Django 4.1.2 on 2022-11-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_category_isdefault_category_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
