# Generated by Django 4.1.2 on 2022-11-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_category_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category", unique_together={("name", "id")},
        ),
    ]
