# Generated by Django 4.1.2 on 2022-11-04 21:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0005_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category", unique_together={("name", "generated_user")},
        ),
    ]
