# Generated by Django 4.1.2 on 2022-11-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
