# Generated by Django 4.1 on 2022-11-05 01:35

import accounts.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('insta', models.CharField(blank=True, max_length=20)),
                ('github', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(upload_to='profileimages/')),
                ('name', models.CharField(max_length=10, verbose_name=accounts.models.User)),
                ('birthday', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=20)),
            ],
        ),
    ]
