<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-13 05:26
=======
# Generated by Django 4.1 on 2022-11-13 05:32
>>>>>>> 172fd462cc636a06956301ead70e4484f645846e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
