# Generated by Django 4.1 on 2022-11-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='github',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
