# Generated by Django 4.1 on 2022-11-05 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_alter_contacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phonenumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0-9]?)-?([0-9]{3,4})-?([0-9]{4})')]),
        ),
    ]
