# Generated by Django 4.1 on 2022-11-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_alter_contacts_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='blog',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phonenumber',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
