# Generated by Django 4.1 on 2022-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0009_contacts_blog_alter_contacts_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
