# Generated by Django 4.1 on 2022-11-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0011_alter_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profileimage', models.ImageField(upload_to='profileimages/')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileimage',
        ),
    ]
