# Generated by Django 4.1.2 on 2022-11-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profileimages/당당아코.png', upload_to=''),
        ),
    ]
